"""added category table

Revision ID: dbdbdc708c3c
Revises:
Create Date: 2024-08-27 12:24:46.680641

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbdbdc708c3c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_index(op.f("ix_category_category_id"), "category", ["category_id"], unique=False)
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_index(op.f("ix_category_category_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
